"""added time column in Users Database

Revision ID: 67e58e02ec0d
Revises: 73068e786f1b
Create Date: 2022-07-02 23:23:50.433424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67e58e02ec0d'
down_revision = '73068e786f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('cover_pic',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('cover_pic',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('profile_pic',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
