"""added cover_pic column in database

Revision ID: 73068e786f1b
Revises: fafe4da47bad
Create Date: 2022-07-02 22:47:32.287713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73068e786f1b'
down_revision = 'fafe4da47bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_pic', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cover_pic')

    # ### end Alembic commands ###
